name: side_navigation
description: Provides Flutter navigation by using a sidemenu similar to Drawer or BottomNavigationBar.
version: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
